apiVersion: apps/v1
kind: Deployment
metadata:
  name: anti-affinity-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anti-affinity-app
  template:
    metadata:
      labels:
        app: anti-affinity-app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - anti-affinity-app
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: nginx
