apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-database
spec:
  serviceName: db
  replicas: 3
  selector:
    matchLabels:
      app: my-database
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
      - name: db
        image: postgres:12
        env:
        - name: POSTGRES_PASSWORD
          value: "1234567890"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: my-database
spec:
  clusterIP: None
  selector:
    app: my-database
  ports:
  - port: 5432
